[[search-aggregations-matrix-stats-aggregation]]
=== 矩阵统计

`matrix_stats` 聚合是一种数值聚合，这种聚合会针对一组文档中的某些字段计算出一下统计信息:

[horizontal]
`count`:: 计算中包含的每个字段的样本数量。
`mean`:: 均值，每个字段的平均值。
`variance`:: 方差，每个字段的样本离散程度。
`skewness`:: 偏度，衡量每个字段分布的不对称性。
`kurtosis`:: 峰度，衡量每个字段分布的形态。
`covariance`:: 协方差，结果为一个矩阵，它定量地描述了两个字段之间变化的相关性。
`correlation`:: 相关系数，协方差矩阵缩放到 -1 到 1 的范围，闭区间。描述字段分布之间的关系。

//////////////////////////

[source,js]
--------------------------------------------------
PUT /statistics/_doc/0
{"poverty": 24.0, "income": 50000.0}

PUT /statistics/_doc/1
{"poverty": 13.0, "income": 95687.0}

PUT /statistics/_doc/2
{"poverty": 69.0, "income": 7890.0}

POST /_refresh
--------------------------------------------------
// NOTCONSOLE
// TESTSETUP

//////////////////////////

下面的示例演示了如何使用矩阵统计来描述收入水平和贫困程度之间的关系。

[source,js]
--------------------------------------------------
GET /_search
{
    "aggs": {
        "statistics": {
            "matrix_stats": {
                "fields": ["poverty", "income"]
            }
        }
    }
}
--------------------------------------------------
// CONSOLE
// TEST[s/_search/_search\?filter_path=aggregations/]

聚合类型是 `matrix_stats` ，`fields` 设置定义了用于计算统计数据的字段集(以数组的形式)。上面的请求返回以下响应:

[source,js]
--------------------------------------------------
{
    ...
    "aggregations": {
        "statistics": {
            "doc_count": 50,
            "fields": [{
                "name": "income",
                "count": 50,
                "mean": 51985.1,
                "variance": 7.383377037755103E7,
                "skewness": 0.5595114003506483,
                "kurtosis": 2.5692365287787124,
                "covariance": {
                    "income": 7.383377037755103E7,
                    "poverty": -21093.65836734694
                },
                "correlation": {
                    "income": 1.0,
                    "poverty": -0.8352655256272504
                }
            }, {
                "name": "poverty",
                "count": 50,
                "mean": 12.732000000000001,
                "variance": 8.637730612244896,
                "skewness": 0.4516049811903419,
                "kurtosis": 2.8615929677997767,
                "covariance": {
                    "income": -21093.65836734694,
                    "poverty": 8.637730612244896
                },
                "correlation": {
                    "income": -0.8352655256272504,
                    "poverty": 1.0
                }
            }]
        }
    }
}
--------------------------------------------------
// TESTRESPONSE[s/\.\.\.//]
// TESTRESPONSE[s/: (\-)?[0-9\.E]+/: $body.$_path/]

`doc_count` 字段表示参与统计计算的文档的数量。

==== 多值字段

`matrix_stats` 聚合将每个文档字段视为独立的样本。
`mode` 参数控制在遇到数组或者多值字段时，讲使用数组中的哪个值。该参数可以使用下列之一:

[horizontal]
`avg`:: （默认）使用所有值的均值。
`min`:: 选取最小的值。
`max`:: 选取最大的值。
`sum`:: 使用所有值的总和。
`median`:: 使用所有值的中值。

==== 缺失值

`missing` 这个参数定义了应该如何处理文档中有缺失值的情况。默认情况下，它们会被忽略，但也可以将其视为有值。实现方法是，通过添加一组字段名与值的对应关系来指定每个字段的默认值

[source,js]
--------------------------------------------------
GET /_search
{
    "aggs": {
        "matrixstats": {
            "matrix_stats": {
                "fields": ["poverty", "income"],
                "missing": {"income" : 50000} <1>
            }
        }
    }
}
--------------------------------------------------
// CONSOLE

<1> 文档中 `income` 字段值有缺失将会使用 `50000` 作为默认值。

==== 脚本

这一类的聚合暂时还不支持使用脚本。
